### ISSUE TITLE
How to use Sillm to execute GPTQ or GGUF models

### ISSUE THREAD

**Issue by White-Friday** [armbues/SiLLM#14]
eg:python -m sillm.server /path/to/model --port 8000
How to add parameters to specify the quantization format, and how to add parameters to specify GPU or CPU?

**Comment by armbues** [comment]
The quantization is automatically determined while loading the GGUF file.

For reference see the [documentation](https://ml-explore.github.io/mlx/build/html/python/_autosummary/mlx.core.load.html) of `mx.load`.

**Comment by armbues** [comment]
Also, there is no need to specify GPU or CPU as that is handled by MLX internally.
