### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by AlgebraicAmin01** [armbues/SiLLM#7]
~% conda create -n newenv python=3.11  

Using cached protobuf-4.25.3-cp37-abi3-macosx_10_9_universal2.whl (394 kB)
Installing collected packages: protobuf
  Attempting uninstall: protobuf
    Found existing installation: protobuf 5.26.1
    Uninstalling protobuf-5.26.1:
      Successfully uninstalled protobuf-5.26.1
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
sillm-mlx 0.1.3 requires protobuf>=5.26.1, but you have protobuf 4.25.3 which is incompatible.

.
.
.

  raise ValueError("Please set the environment variable SILLM_MODEL_DIR to the directory containing the models.")
ValueError: Please set the environment variable SILLM_MODEL_DIR to the directory containing the models.

**Comment by armbues** [comment]
The protobuf version warning during installation shouldn't cause any issues and is unrelated.

The ValueError is not related to the installation but when running the web frontend via `app.py`. As outlined in the error message, you need to set an environment variable to specify the directory where your models are stored:
`export SILLM_MODEL_DIR=/path/to/models`
